/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import businessentity.OpenBarOrder;
import businessentity.OpenKitchenOrder;
import businesslogic.SystemManager;
import datastorage.OpenBarOrdersDAO;
import datastorage.OpenKitchenOrdersDAO;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author 23IVP4A2
 */
public class ScreenInfoFrame extends javax.swing.JFrame {
    
    

    
    
    public ScreenInfoFrame() {
        initComponents();
        


        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH); 

        jButton1.setText("Uitloggen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jFrame1.dispose();
                            MyLogin ui = new MyLogin();
            }
        });

        jButton2.setText("Accepteren");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Gereed");

        
        // Tabel BarOrders
        OpenBarOrdersDAO daoBar = new OpenBarOrdersDAO();

        ArrayList<OpenBarOrder> barOrders = daoBar.getAllOpenBarOrders(null);
        
        DefaultTableModel model = new DefaultTableModel();
        
        Object[] columnsName = new Object[5];
        
        columnsName[0] = "Barorder ID";
        columnsName[1] = "Drankje";
        columnsName[2] = "Tafel Nummer";
        columnsName[3] = "Hoeveelheid";
        columnsName[4] = "Status";
        
        model.setColumnIdentifiers(columnsName);
        
        Object[] rowData = new Object[5];
        
        for(int i = 0; i < barOrders.size(); i++){
            
            rowData[0] = barOrders.get(i).getBarOrderId();
             rowData[1] = barOrders.get(i).getDrinkName();
              rowData[2] = barOrders.get(i).getTableNr();
               rowData[3] = barOrders.get(i).getQuantity();
                rowData[4] = barOrders.get(i).getStatusName();
               
               model.addRow(rowData);
        }
        
        jTable1.setModel(model);
        
                // Tabel KitchenOrders
        OpenKitchenOrdersDAO daoKitchen = new OpenKitchenOrdersDAO();

        ArrayList<OpenKitchenOrder> kitchenOrders = daoKitchen.getAllOpenKitchenOrders(null);
        
        DefaultTableModel model2 = new DefaultTableModel();
        
        Object[] columnsName2 = new Object[5];
        
        columnsName2[0] = "Keukenorder ID";
        columnsName2[1] = "Tafelnummer";
        columnsName2[2] = "Gerecht";
        columnsName2[3] = "Hoeveelheid";
        columnsName2[4] = "Status";

        
        model2.setColumnIdentifiers(columnsName2);
        
        Object[] rowData2 = new Object[5];
        
        for(int i = 0; i < kitchenOrders.size(); i++){
            

              rowData2[0] = kitchenOrders.get(i).getKitchenOrderId();
                rowData2[1] = kitchenOrders.get(i).getTableNr();
                 rowData2[2] = kitchenOrders.get(i).getDishName();
                  rowData2[3] = kitchenOrders.get(i).getQuantity();
                   rowData2[4] = kitchenOrders.get(i).getStatusName();
                                  
               
               model2.addRow(rowData2);
        }
        
        jTable2.setModel(model2);
        
        jScrollPane3.setViewportView(jTable2);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))))
                .addContainerGap(398, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                         
       
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        
                                      

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    // End of variables declaration                   
}
